version: '3.8'

services:
  db:
    restart: 'always'
    image: ${DATABASE_IMAGE}
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASS}
      - POSTGRES_DB=${DATABASE_NAME}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      interval: '10s'
      timeout: '30s'
      retries: 5
      start_period: '20s'
    ports:
      - '${DATABASE_PORT}:${DATABASE_PORT}'
    networks:
      - backend
    volumes:
      - 'database:/var/lib/postgresql/data'
networks:
  backend:

volumes:
  database: